# Generated by Django 4.2.6 on 2023-10-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlibrary', '0002_book_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='books/'),
        ),
    ]
