# Generated by Django 4.2.6 on 2023-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlibrary', '0003_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=80),
        ),
    ]
