# Generated by Django 4.2.6 on 2023-10-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
